"""The `mason-agent` skill is what a running Mason knows about itself.

Mason is a detached fork with no docs site: the skill routes unknown-feature
questions to the in-repo tool manifest (`tools/index/INDEX.md`, regenerated by
scripts/gen_tool_index.py) instead of a published llms.txt. These tests keep
that routing honest: the index has to be where the skill says it is and cover
the tool surface, otherwise a shipped feature is invisible and the agent
answers "Mason can't do that."
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
SKILL_DIR = REPO / "skills" / "autonomous-ai-agents" / "mason-agent"
SKILL_MD = SKILL_DIR / "SKILL.md"
TOOL_INDEX = REPO / "tools" / "index" / "INDEX.md"
TOOL_SUMMARIES = REPO / "tools" / "index" / "summaries.json"


@pytest.fixture(scope="module")
def skill_text() -> str:
    return SKILL_MD.read_text(encoding="utf-8")


def test_every_referenced_file_exists(skill_text):
    """Routing a question to a file that isn't there is a dead end."""
    targets = set(re.findall(r"`((?:references|templates)/[^`]+)`", skill_text))

    assert targets, "the skill's routing table no longer references any files"
    for target in sorted(targets):
        assert (SKILL_DIR / target).exists(), f"SKILL.md routes to missing {target}"


def test_every_reference_is_reachable_from_the_skill(skill_text):
    """An unrouted reference is one the agent will never think to open.

    This is the failure that produced the original complaint: content can exist
    and still be invisible because nothing points at it.
    """
    on_disk = {f"references/{path.name}" for path in (SKILL_DIR / "references").glob("*.md")}
    routed = set(re.findall(r"`(references/[^`]+)`", skill_text))

    assert not (on_disk - routed), (
        f"reference files no reader will ever reach: {sorted(on_disk - routed)} — "
        "add a routing-table row in SKILL.md"
    )


def test_unknown_features_route_to_the_published_index(skill_text):
    """The catch-all is what makes coverage of the whole product possible."""
    assert "tools/index/INDEX.md" in skill_text
    # read_file/terminal are always available — the index needs no web tools.
    assert "read_file" in skill_text


def test_the_index_is_published_where_the_skill_says_it_is(skill_text):
    """A skill pointing at an index nobody generates is worse than no routing."""
    assert TOOL_INDEX.exists(), "tools/index/INDEX.md missing — run scripts/gen_tool_index.py"
    body = TOOL_INDEX.read_text(encoding="utf-8")
    summaries = json.loads(TOOL_SUMMARIES.read_text(encoding="utf-8"))
    assert len(summaries) >= 50, "index suspiciously small — regenerate it"
    for name in ("terminal", "read_file", "memory", "recall_backup"):
        assert f"- {name}:" in body, f"core tool {name} missing from the published index"
